### ISSUE TITLE
Idea: download of full production data

### ISSUE THREAD

**Issue by juicejuice** [cabberley/Home-Assistant_Redback_Invertor_Mode_Set#2]
Just an idea seeing as your integration has access to the Redback portal. There is an API endpoint `https://portal.redbacktech.com/charts/GetDataBands` that is used by the portal to download production data. This data is then fed into Highcharts to draw the charts for the ANALYSIS tab. This contains loads of useful data including the PV string currents and voltages which are not available via any other method that I'm aware of. I tested today and it is possible to download this data once `.AspNet.ApplicationCookie` is available.

**Comment by cabberley** [comment]
Thanks @juicejuice that data is coming from the redback API. If you look at the api.redback tech.com and change to the v2.21 in the dropdown at the top you will find some same but different RestAPIs, the one in the image below is the one that gets that data as well as the individual battery data. My integration pulls all this into HA. Originally the portal didn't use it the APIs but they have been gradually changing it in the backend to use the same published APIs. From memory you do have to Auth against a v2.0 and the only datapoint in the analysis graph that isn't available in the API is the backup circuit load W. The only thing I need to use the portal for is to set the inverter to Auto without a time constraint. It's in their backlog to expose it via the API, the API only has an option to put a duration on controlling inverter mode. 

 ![image](https://github.com/user-attachments/assets/d4245fe7-b14b-4941-824e-c8017205abd9)

Values are 0 as it's 4am and raining so no solar just yet
![image](https://github.com/user-attachments/assets/05464940-735e-4be5-981c-627e738d3690)

![image](https://github.com/user-attachments/assets/eaa7b1f7-52a8-4bb6-ac72-2f26c322d74f)

**Comment by juicejuice** [comment]
Thanks, good tip @cabberley! I had assumed those extra API versions were unavailable as I get "Auth Error Error: Bad Request" on the API site. They work by HTTP request though! I'll see if I can update my integration to gain access to these data points. The only other interesting data points missing versus the charting tool are real-time load on the normal and backup phases.
